"""audit identity corrections and queue manual source syncs

Revision ID: 56db542e0227
Revises: d6443cc934a6
"""

import sqlalchemy as sa
from alembic import op

revision = "56db542e0227"
down_revision = "d6443cc934a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("active_source", sa.String(length=80), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ingestion_run_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_sync_requests_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_sync_requests_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_requests")),
        sa.UniqueConstraint("active_source", name=op.f("uq_sync_requests_active_source")),
    )
    op.create_index(
        op.f("ix_sync_requests_source_id"), "sync_requests", ["source_id"], unique=False
    )
    op.create_table(
        "deployment_identity_overrides",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=64), nullable=False),
        sa.Column("previous_model_id", sa.String(length=64), nullable=False),
        sa.Column("target_model_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_url", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
            name=op.f("fk_deployment_identity_overrides_deployment_id_deployments"),
        ),
        sa.ForeignKeyConstraint(
            ["previous_model_id"],
            ["models.id"],
            name=op.f("fk_deployment_identity_overrides_previous_model_id_models"),
        ),
        sa.ForeignKeyConstraint(
            ["target_model_id"],
            ["models.id"],
            name=op.f("fk_deployment_identity_overrides_target_model_id_models"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployment_identity_overrides")),
    )
    op.create_index(
        op.f("ix_deployment_identity_overrides_deployment_id"),
        "deployment_identity_overrides",
        ["deployment_id"],
        unique=False,
    )
    with op.batch_alter_table("model_policies") as batch:
        batch.add_column(sa.Column("approved_deployment_id", sa.String(length=64), nullable=True))
        batch.create_foreign_key(
            "fk_model_policies_approved_deployment_id_deployments",
            "deployments",
            ["approved_deployment_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_policies") as batch:
        batch.drop_constraint(
            "fk_model_policies_approved_deployment_id_deployments", type_="foreignkey"
        )
        batch.drop_column("approved_deployment_id")
    op.drop_index(
        op.f("ix_deployment_identity_overrides_deployment_id"),
        table_name="deployment_identity_overrides",
    )
    op.drop_table("deployment_identity_overrides")
    op.drop_index(op.f("ix_sync_requests_source_id"), table_name="sync_requests")
    op.drop_table("sync_requests")
    # ### end Alembic commands ###
