"""index current model and deployment attributes

Revision ID: 5f7ef2b5a319
Revises: 822ea59dfae1
"""

import sqlalchemy as sa
from alembic import op

revision = "5f7ef2b5a319"
down_revision = "822ea59dfae1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("deployments", sa.Column("context_window", sa.Integer(), nullable=True))
    op.add_column("deployments", sa.Column("max_output", sa.Integer(), nullable=True))
    op.add_column("deployments", sa.Column("tool_calling", sa.Boolean(), nullable=True))
    op.add_column("deployments", sa.Column("structured_output", sa.Boolean(), nullable=True))
    op.add_column("deployments", sa.Column("image_input", sa.Boolean(), nullable=True))
    op.add_column("deployments", sa.Column("reasoning", sa.Boolean(), nullable=True))
    op.add_column("deployments", sa.Column("availability", sa.String(length=40), nullable=True))
    op.add_column("models", sa.Column("family", sa.String(length=300), nullable=True))
    op.add_column("models", sa.Column("context_window", sa.Integer(), nullable=True))
    op.add_column("models", sa.Column("open_weights", sa.Boolean(), nullable=True))
    op.add_column("models", sa.Column("release_date", sa.String(length=40), nullable=True))
    op.create_index(op.f("ix_models_family"), "models", ["family"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_models_family"), table_name="models")
    op.drop_column("models", "release_date")
    op.drop_column("models", "open_weights")
    op.drop_column("models", "context_window")
    op.drop_column("models", "family")
    op.drop_column("deployments", "availability")
    op.drop_column("deployments", "reasoning")
    op.drop_column("deployments", "image_input")
    op.drop_column("deployments", "structured_output")
    op.drop_column("deployments", "tool_calling")
    op.drop_column("deployments", "max_output")
    op.drop_column("deployments", "context_window")
    # ### end Alembic commands ###
