"""catalog and evidence foundation

Revision ID: 7363216726fe
Revises:
"""

import sqlalchemy as sa
from alembic import op

revision = "7363216726fe"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("id", sa.String(length=300), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
    )
    op.create_table(
        "recommendation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("algorithm_version", sa.String(length=40), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_runs")),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("terms_url", sa.Text(), nullable=False),
        sa.Column("attribution", sa.Text(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("last_success_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
    )
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("records_discovered", sa.Integer(), nullable=False),
        sa.Column("records_changed", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_ingestion_runs_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index(
        op.f("ix_ingestion_runs_source_id"), "ingestion_runs", ["source_id"], unique=False
    )
    op.create_table(
        "models",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("identity_key", sa.String(length=800), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("publisher_id", sa.String(length=300), nullable=True),
        sa.Column("identity_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["publisher_id"],
            ["organizations.id"],
            name=op.f("fk_models_publisher_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
        sa.UniqueConstraint("identity_key", name=op.f("uq_models_identity_key")),
    )
    op.create_index(op.f("ix_models_name"), "models", ["name"], unique=False)
    op.create_index(op.f("ix_models_publisher_id"), "models", ["publisher_id"], unique=False)
    op.create_table(
        "providers",
        sa.Column("id", sa.String(length=300), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("organization_id", sa.String(length=300), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_providers_organization_id_organizations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_providers")),
    )
    op.create_table(
        "raw_snapshots",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("byte_length", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_raw_snapshots_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_raw_snapshots")),
    )
    op.create_index(
        op.f("ix_raw_snapshots_content_hash"), "raw_snapshots", ["content_hash"], unique=False
    )
    op.create_table(
        "deployments",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("access_provider_id", sa.String(length=300), nullable=False),
        sa.Column("upstream_provider_id", sa.String(length=300), nullable=True),
        sa.Column("api_model_id", sa.String(length=800), nullable=False),
        sa.Column("variant", sa.String(length=500), nullable=False),
        sa.Column("listing_kind", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_provider_id"],
            ["providers.id"],
            name=op.f("fk_deployments_access_provider_id_providers"),
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("fk_deployments_model_id_models")
        ),
        sa.ForeignKeyConstraint(
            ["upstream_provider_id"],
            ["providers.id"],
            name=op.f("fk_deployments_upstream_provider_id_providers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployments")),
        sa.UniqueConstraint(
            "access_provider_id",
            "api_model_id",
            "variant",
            name=op.f("uq_deployments_access_provider_id"),
        ),
    )
    op.create_index(
        op.f("ix_deployments_access_provider_id"),
        "deployments",
        ["access_provider_id"],
        unique=False,
    )
    op.create_index(op.f("ix_deployments_model_id"), "deployments", ["model_id"], unique=False)
    op.create_table(
        "fetch_receipts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("etag", sa.Text(), nullable=True),
        sa.Column("last_modified", sa.Text(), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["ingestion_runs.id"], name=op.f("fk_fetch_receipts_run_id_ingestion_runs")
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_snapshots.id"],
            name=op.f("fk_fetch_receipts_snapshot_id_raw_snapshots"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fetch_receipts")),
    )
    op.create_index(op.f("ix_fetch_receipts_run_id"), "fetch_receipts", ["run_id"], unique=False)
    op.create_table(
        "source_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=800), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("raw", sa.JSON(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["raw_snapshots.id"],
            name=op.f("fk_source_records_snapshot_id_raw_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_source_records_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_records")),
    )
    op.create_index(
        op.f("ix_source_records_source_id"), "source_records", ["source_id"], unique=False
    )
    op.create_table(
        "benchmark_definitions",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=60), nullable=False),
        sa.Column("owner", sa.String(length=300), nullable=True),
        sa.Column("higher_is_better", sa.Boolean(), nullable=True),
        sa.Column("score_min", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("score_max", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("source_record_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_benchmark_definitions_source_record_id_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_definitions")),
        sa.UniqueConstraint("name", "version", name=op.f("uq_benchmark_definitions_name")),
    )
    op.create_table(
        "deployment_aliases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("external_id", sa.String(length=900), nullable=False),
        sa.Column("deployment_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
            name=op.f("fk_deployment_aliases_deployment_id_deployments"),
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["source_records.id"],
            name=op.f("fk_deployment_aliases_evidence_id_source_records"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_deployment_aliases_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deployment_aliases")),
        sa.UniqueConstraint(
            "source_id", "external_id", name=op.f("uq_deployment_aliases_source_id")
        ),
    )
    op.create_index(
        op.f("ix_deployment_aliases_deployment_id"),
        "deployment_aliases",
        ["deployment_id"],
        unique=False,
    )
    op.create_table(
        "fact_observations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.String(length=300), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("source_record_id", sa.String(length=64), nullable=False),
        sa.Column("verification", sa.String(length=40), nullable=False),
        sa.Column("authority", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_fact_observations_source_record_id_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_observations")),
    )
    op.create_index(
        "ix_fact_entity_field",
        "fact_observations",
        ["entity_type", "entity_id", "field"],
        unique=False,
    )
    op.create_table(
        "market_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.String(length=300), nullable=False),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("old_value", sa.JSON(), nullable=True),
        sa.Column("new_value", sa.JSON(), nullable=True),
        sa.Column("source_record_id", sa.String(length=64), nullable=False),
        sa.Column("importance", sa.String(length=30), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_market_events_source_record_id_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_events")),
    )
    op.create_index(
        op.f("ix_market_events_detected_at"), "market_events", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_market_events_entity_id"), "market_events", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_market_events_event_type"), "market_events", ["event_type"], unique=False
    )
    op.create_table(
        "model_aliases",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("external_id", sa.String(length=800), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("evidence_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["source_records.id"],
            name=op.f("fk_model_aliases_evidence_id_source_records"),
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("fk_model_aliases_model_id_models")
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_model_aliases_source_id_sources")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_aliases")),
        sa.UniqueConstraint("source_id", "external_id", name=op.f("uq_model_aliases_source_id")),
    )
    op.create_index(op.f("ix_model_aliases_model_id"), "model_aliases", ["model_id"], unique=False)
    op.create_table(
        "pricing_observations",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("deployment_id", sa.String(length=64), nullable=False),
        sa.Column("metric", sa.String(length=60), nullable=False),
        sa.Column("amount", sa.Numeric(precision=30, scale=12), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit", sa.String(length=40), nullable=False),
        sa.Column("source_record_id", sa.String(length=64), nullable=False),
        sa.Column("native_amount", sa.String(length=100), nullable=False),
        sa.Column("native_quantity", sa.Integer(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "amount >= 0 AND quantity > 0 AND native_quantity > 0",
            name=op.f("ck_pricing_observations_positive_price"),
        ),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
            name=op.f("fk_pricing_observations_deployment_id_deployments"),
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_pricing_observations_source_record_id_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pricing_observations")),
    )
    op.create_index(
        op.f("ix_pricing_observations_deployment_id"),
        "pricing_observations",
        ["deployment_id"],
        unique=False,
    )
    op.create_table(
        "benchmark_results",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=False),
        sa.Column("benchmark_id", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("verification", sa.String(length=40), nullable=False),
        sa.Column("evaluator", sa.String(length=300), nullable=False),
        sa.Column("source_record_id", sa.String(length=64), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["benchmark_id"],
            ["benchmark_definitions.id"],
            name=op.f("fk_benchmark_results_benchmark_id_benchmark_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.id"], name=op.f("fk_benchmark_results_model_id_models")
        ),
        sa.ForeignKeyConstraint(
            ["source_record_id"],
            ["source_records.id"],
            name=op.f("fk_benchmark_results_source_record_id_source_records"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_benchmark_results")),
    )
    op.create_index(
        op.f("ix_benchmark_results_benchmark_id"),
        "benchmark_results",
        ["benchmark_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_benchmark_results_model_id"), "benchmark_results", ["model_id"], unique=False
    )
    op.create_table(
        "current_facts",
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.String(length=300), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("observation_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["fact_observations.id"],
            name=op.f("fk_current_facts_observation_id_fact_observations"),
        ),
        sa.PrimaryKeyConstraint("entity_type", "entity_id", "field", name=op.f("pk_current_facts")),
    )
    op.create_table(
        "source_conflicts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.String(length=300), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("observation_a", sa.String(length=64), nullable=False),
        sa.Column("observation_b", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("resolution", sa.Text(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["observation_a"],
            ["fact_observations.id"],
            name=op.f("fk_source_conflicts_observation_a_fact_observations"),
        ),
        sa.ForeignKeyConstraint(
            ["observation_b"],
            ["fact_observations.id"],
            name=op.f("fk_source_conflicts_observation_b_fact_observations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_conflicts")),
    )
    op.create_index(
        op.f("ix_source_conflicts_entity_id"), "source_conflicts", ["entity_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_conflicts_entity_id"), table_name="source_conflicts")
    op.drop_table("source_conflicts")
    op.drop_table("current_facts")
    op.drop_index(op.f("ix_benchmark_results_model_id"), table_name="benchmark_results")
    op.drop_index(op.f("ix_benchmark_results_benchmark_id"), table_name="benchmark_results")
    op.drop_table("benchmark_results")
    op.drop_index(op.f("ix_pricing_observations_deployment_id"), table_name="pricing_observations")
    op.drop_table("pricing_observations")
    op.drop_index(op.f("ix_model_aliases_model_id"), table_name="model_aliases")
    op.drop_table("model_aliases")
    op.drop_index(op.f("ix_market_events_event_type"), table_name="market_events")
    op.drop_index(op.f("ix_market_events_entity_id"), table_name="market_events")
    op.drop_index(op.f("ix_market_events_detected_at"), table_name="market_events")
    op.drop_table("market_events")
    op.drop_index("ix_fact_entity_field", table_name="fact_observations")
    op.drop_table("fact_observations")
    op.drop_index(op.f("ix_deployment_aliases_deployment_id"), table_name="deployment_aliases")
    op.drop_table("deployment_aliases")
    op.drop_table("benchmark_definitions")
    op.drop_index(op.f("ix_source_records_source_id"), table_name="source_records")
    op.drop_table("source_records")
    op.drop_index(op.f("ix_fetch_receipts_run_id"), table_name="fetch_receipts")
    op.drop_table("fetch_receipts")
    op.drop_index(op.f("ix_deployments_model_id"), table_name="deployments")
    op.drop_index(op.f("ix_deployments_access_provider_id"), table_name="deployments")
    op.drop_table("deployments")
    op.drop_index(op.f("ix_raw_snapshots_content_hash"), table_name="raw_snapshots")
    op.drop_table("raw_snapshots")
    op.drop_table("providers")
    op.drop_index(op.f("ix_models_publisher_id"), table_name="models")
    op.drop_index(op.f("ix_models_name"), table_name="models")
    op.drop_table("models")
    op.drop_index(op.f("ix_ingestion_runs_source_id"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    op.drop_table("sources")
    op.drop_table("recommendation_runs")
    op.drop_table("organizations")
    # ### end Alembic commands ###
