"""track current claims per source

Revision ID: 8f708c750d19
Revises: 7363216726fe
"""

import sqlalchemy as sa
from alembic import op

revision = "8f708c750d19"
down_revision = "7363216726fe"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_claims",
        sa.Column("source_id", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=30), nullable=False),
        sa.Column("entity_id", sa.String(length=300), nullable=False),
        sa.Column("field", sa.String(length=100), nullable=False),
        sa.Column("observation_id", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["observation_id"],
            ["fact_observations.id"],
            name=op.f("fk_source_claims_observation_id_fact_observations"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["sources.id"], name=op.f("fk_source_claims_source_id_sources")
        ),
        sa.PrimaryKeyConstraint(
            "source_id", "entity_type", "entity_id", "field", name=op.f("pk_source_claims")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("source_claims")
    # ### end Alembic commands ###
