"""private harness telemetry and versioned evaluation lab

Revision ID: c14de101428b
Revises: 5f7ef2b5a319
"""

import sqlalchemy as sa
from alembic import op

revision = "c14de101428b"
down_revision = "5f7ef2b5a319"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_suites",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_suites")),
        sa.UniqueConstraint("name", "version", name=op.f("uq_evaluation_suites_name")),
    )
    op.create_table(
        "harnesses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_harnesses")),
        sa.UniqueConstraint("name", name=op.f("uq_harnesses_name")),
    )
    op.create_table(
        "evaluation_cases",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("suite_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("input", sa.Text(), nullable=False),
        sa.Column("reference", sa.Text(), nullable=False),
        sa.Column("scorer", sa.String(length=40), nullable=False),
        sa.Column("scorer_version", sa.String(length=40), nullable=False),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["evaluation_suites.id"],
            name=op.f("fk_evaluation_cases_suite_id_evaluation_suites"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_cases")),
    )
    op.create_index(
        op.f("ix_evaluation_cases_suite_id"), "evaluation_cases", ["suite_id"], unique=False
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("suite_id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evaluator_version", sa.String(length=100), nullable=False),
        sa.Column("score", sa.Numeric(precision=10, scale=8), nullable=False),
        sa.Column("results", sa.JSON(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
            name=op.f("fk_evaluation_runs_deployment_id_deployments"),
        ),
        sa.ForeignKeyConstraint(
            ["suite_id"],
            ["evaluation_suites.id"],
            name=op.f("fk_evaluation_runs_suite_id_evaluation_suites"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluation_runs")),
    )
    op.create_index(
        op.f("ix_evaluation_runs_deployment_id"), "evaluation_runs", ["deployment_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_runs_suite_id"), "evaluation_runs", ["suite_id"], unique=False
    )
    op.create_table(
        "harness_roles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("harness_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("default_deployment_id", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["default_deployment_id"],
            ["deployments.id"],
            name=op.f("fk_harness_roles_default_deployment_id_deployments"),
        ),
        sa.ForeignKeyConstraint(
            ["harness_id"], ["harnesses.id"], name=op.f("fk_harness_roles_harness_id_harnesses")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_harness_roles")),
        sa.UniqueConstraint("harness_id", "name", name=op.f("uq_harness_roles_harness_id")),
    )
    op.create_index(
        op.f("ix_harness_roles_harness_id"), "harness_roles", ["harness_id"], unique=False
    )
    op.create_table(
        "harness_run_telemetry",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("external_run_id", sa.String(length=200), nullable=False),
        sa.Column("harness_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("deployment_id", sa.String(length=64), nullable=False),
        sa.Column("task_type", sa.String(length=100), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cached_tokens", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Numeric(precision=60, scale=30), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("error_category", sa.String(length=100), nullable=True),
        sa.Column("quality_score", sa.Numeric(precision=10, scale=8), nullable=True),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["deployment_id"],
            ["deployments.id"],
            name=op.f("fk_harness_run_telemetry_deployment_id_deployments"),
        ),
        sa.ForeignKeyConstraint(
            ["harness_id"],
            ["harnesses.id"],
            name=op.f("fk_harness_run_telemetry_harness_id_harnesses"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["harness_roles.id"],
            name=op.f("fk_harness_run_telemetry_role_id_harness_roles"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_harness_run_telemetry")),
        sa.UniqueConstraint(
            "harness_id", "external_run_id", name=op.f("uq_harness_run_telemetry_harness_id")
        ),
    )
    op.create_index(
        op.f("ix_harness_run_telemetry_deployment_id"),
        "harness_run_telemetry",
        ["deployment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_harness_run_telemetry_harness_id"),
        "harness_run_telemetry",
        ["harness_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_harness_run_telemetry_role_id"), "harness_run_telemetry", ["role_id"], unique=False
    )
    op.create_table(
        "model_policies",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approval_note", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"], ["harness_roles.id"], name=op.f("fk_model_policies_role_id_harness_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_model_policies")),
        sa.UniqueConstraint("role_id", "version", name=op.f("uq_model_policies_role_id")),
    )
    op.create_index(op.f("ix_model_policies_role_id"), "model_policies", ["role_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_model_policies_role_id"), table_name="model_policies")
    op.drop_table("model_policies")
    op.drop_index(op.f("ix_harness_run_telemetry_role_id"), table_name="harness_run_telemetry")
    op.drop_index(op.f("ix_harness_run_telemetry_harness_id"), table_name="harness_run_telemetry")
    op.drop_index(
        op.f("ix_harness_run_telemetry_deployment_id"), table_name="harness_run_telemetry"
    )
    op.drop_table("harness_run_telemetry")
    op.drop_index(op.f("ix_harness_roles_harness_id"), table_name="harness_roles")
    op.drop_table("harness_roles")
    op.drop_index(op.f("ix_evaluation_runs_suite_id"), table_name="evaluation_runs")
    op.drop_index(op.f("ix_evaluation_runs_deployment_id"), table_name="evaluation_runs")
    op.drop_table("evaluation_runs")
    op.drop_index(op.f("ix_evaluation_cases_suite_id"), table_name="evaluation_cases")
    op.drop_table("evaluation_cases")
    op.drop_table("harnesses")
    op.drop_table("evaluation_suites")
    # ### end Alembic commands ###
